services:

  app:
    build: .
    container_name: ninety-backend
    restart: unless-stopped

    environment:

      # =========================
      # Spring
      # =========================
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}

      # =========================
      # MySQL / Aiven
      # =========================
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # =========================
      # Redis / Upstash
      # =========================
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}

      # =========================
      # JWT
      # =========================
      JWT_SECRET: ${JWT_SECRET}
      JWT_ACCESS_EXP: ${JWT_ACCESS_EXP}
      JWT_REFRESH_EXP: ${JWT_REFRESH_EXP}

      # =========================
      # OTP
      # =========================
      OTP_LENGTH: ${OTP_LENGTH:-6}
      OTP_EXPIRY_MIN: ${OTP_EXPIRY_MIN}

      # =========================
      # Gemini
      # =========================
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: ${GEMINI_MODEL}

      # =========================
      # Resend
      # =========================
      RESEND_API_KEY: ${RESEND_API_KEY}
      RESEND_FROM_EMAIL: ${RESEND_FROM_EMAIL}

    ports:
      - "${APP_PORT:-8080}:8080"

    volumes:
      - ./logs:/app/logs